"use client";
import { useState } from "react";
import Link from "next/link";
import styles from "./styles.module.css";

const tabs = ["Deux lieux", "Objectif du groupe", "Billetterie", "Qui est dispo ?"];
const days = ["Vendredi 23 octobre", "Samedi 24 octobre"];
export default function IdeasPreview() {
  const [tab, setTab] = useState(0);
  const [choice, setChoice] = useState<number | null>(null);
  const [count, setCount] = useState(5);
  const [confirmed, setConfirmed] = useState(false);
  const [ticket, setTicket] = useState(false);
  const [day, setDay] = useState(0);
  const [showNames, setShowNames] = useState(true);
  const [available, setAvailable] = useState([false, false]);
  const names = day === 0 ? ["Camille", "Nicolas", "Léa"] : ["Nicolas", "Sarah"];
  return <div className={styles.page}><header className={styles.header}><b>BIMA</b><span>Le labo · preview uniquement</span></header>
    <main className={styles.main}><p className={styles.eyebrow}>ON TESTE DES IDÉES</p><h1>Et si on faisait comme ça ?</h1><p className={styles.intro}>Quatre pistes à essayer. Des données fictives, aucune vraie sortie modifiée.</p><Link className={styles.back} href="/preview/invitation">← Revoir le formulaire de participation</Link>
      <nav className={styles.tabs} aria-label="Exemples à explorer">{tabs.map((label,index) => <button key={label} aria-pressed={tab === index} onClick={() => setTab(index)}>{index+2}. {label}</button>)}</nav>
      <section className={styles.card} aria-label={tabs[tab]}>
        {tab === 0 && <><p className={styles.eyebrow}>CÔTÉ INVITÉ · PRÉFÉRENCE DE LIEU</p><h2>On se retrouve où ?</h2><p>Nicolas hésite entre deux plans. Choisis celui qui te tente le plus.</p><div className={styles.places}>{["Une partie de bowling", "Un resto italien"].map((name,index)=><button className={`${styles.place} ${choice === index ? styles.selected : ""}`} key={name} aria-pressed={choice === index} onClick={()=>setChoice(index)}><span className={styles.art} aria-hidden="true">{index === 0 ? "🎳" : "🍝"}</span><strong>{name}</strong><span>Conflans-Sainte-Honorine</span><b>{index === 0 ? "20 €" : "25 €"} / personne</b><small>{choice === index ? "✓ Mon choix" : "Choisir ce lieu"}</small></button>)}</div><p className={styles.notice} role="status">{choice === null ? "Deux alternatives : la sortie aura lieu dans un seul de ces endroits." : `Préférence notée pour ${choice === 0 ? "le bowling" : "le restaurant"}. Tu peux changer d’avis.`}</p><p className={styles.caption}>Le vote aide Nicolas à choisir. Il confirme ensuite le lieu et la date. Dans le vrai parcours, ce choix accompagnerait les disponibilités.</p></>}
        {tab === 1 && <><p className={styles.eyebrow}>CÔTÉ ORGANISATEUR · SUIVI</p><h2>{confirmed ? "Le bowling est calé !" : "À 6, on se lance ?"}</h2><p>Vendredi 23 octobre · 19 h<br/>Objectif : 6 personnes · 8 places maximum, toi inclus.</p><div className={styles.score}><strong>{count}<small> / 6</small></strong><span>personnes disponibles sur cette date</span><progress value={Math.min(count,6)} max={6} aria-label="Progression vers six personnes" /></div><p className={styles.notice} role="status">{confirmed ? "Confirmation simulée. Aucun message envoyé." : count < 6 ? `Encore ${6-count} personne${6-count>1 ? "s" : ""} pour atteindre ton objectif.` : "Objectif atteint ! Vérifie le lieu avant de confirmer."}</p><button className={styles.primary} disabled={confirmed} onClick={()=>setConfirmed(true)}>{confirmed ? "✓ Sortie confirmée" : count < 6 ? `Confirmer quand même à ${count}` : "Confirmer cette date"}</button><div className={styles.controls}><span>Simuler les réponses</span><button disabled={count<=1} aria-label="Retirer une personne disponible" onClick={()=>{setCount(count-1);setConfirmed(false);}}>−</button><button disabled={count>=8} aria-label="Ajouter une personne disponible" onClick={()=>{setCount(count+1);setConfirmed(false);}}>+</button></div><p className={styles.caption}>L’objectif est un repère, pas un blocage. La confirmation reste ta décision, même si le minimum souhaité n’est pas atteint.</p></>}
        {tab === 2 && <><p className={styles.eyebrow}>CÔTÉ INVITÉ · SORTIE CONFIRMÉE</p><h2>Concert entre potes 🎶</h2><p>Samedi 24 octobre · 20 h<br/>Paris · billet estimé à 30 €</p><div className={styles.ticket}><strong>Ta place reste à réserver</strong><p>La date est calée. Chaque personne achète son billet sur la billetterie du concert.</p><button className={styles.primary} onClick={()=>setTicket(!ticket)}>Voir les billets ↗</button>{ticket && <p className={styles.notice} role="status">Dans la vraie sortie, ce lien ouvrirait la billetterie choisie par l’organisateur. Ici, aucun achat ni site marchand n’est ouvert.</p>}</div><p className={styles.caption}>Répondre présent sur BIMA ne réserve pas de billet. Le lien serait facultatif et renseigné par l’organisateur.</p></>}
        {tab === 3 && <><p className={styles.eyebrow}>CÔTÉ INVITÉ · AVANT CONFIRMATION</p><h2>Qui est dispo avec toi ?</h2><p>Un aperçu par date, juste avant ton choix.</p><div className={styles.days}>{days.map((label,index)=><button key={label} className={day === index ? styles.selected : ""} aria-pressed={day===index} onClick={()=>setDay(index)}>{label}</button>)}</div><div className={styles.people} aria-live="polite">{showNames ? <><div className={styles.avatars} aria-hidden="true">{names.map(name=><span key={name}>{name.slice(0,1)}</span>)}</div><strong>{names.join(", ")}</strong><p>sont disponibles ce jour-là{available[day] ? ", et toi aussi" : ""}.</p></> : <strong>{names.length + (available[day] ? 1 : 0)} personnes disponibles ce jour-là.</strong>}</div><button className={styles.primary} aria-pressed={available[day]} onClick={()=>setAvailable(available.map((value,index)=>index===day ? !value : value))}>{available[day] ? "✓ Je suis dispo · modifier" : "Je suis dispo aussi"}</button><label className={styles.toggle}><input type="checkbox" checked={showNames} onChange={event=>setShowNames(event.target.checked)} /> Comparer avec les prénoms visibles</label><p className={styles.caption}>Disponibles ne veut pas dire présence confirmée. Seuls les prénoms sont montrés, sans coordonnées. Ce choix de visibilité reste à valider avant une intégration.</p></>}
      </section><footer className={styles.footer}>Prototype interactif · rien n’est enregistré · aucune mise en production</footer>
    </main></div>;
}
